name: 'Different Grind : Coffee that''s Kind'
favicon: null
layout_spectrum: 0
typography_spectrum: 0
content_rating:
  adult: false
author:
  name: CaptainCu
  url: ''
  email: ''
title: "Caffeine with a Conscience - not only is it\_Different, it's kind."
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: ''
  appId: ''
color:
  brandColors:
    - '#080506'
    - '#E0DCD4'
    - '#443020'
    - '#CF842F'
    - '#9E9586'
  brandStrength: 0.75
  lightness: 0.375
  saturation: 1
  rhythmicContrast: 0.25
purpose: []
