layout_spectrum: 0
typography_spectrum: 0
color:
  lightness: 0.0006265664
  brandStrength: 0.5308144
  saturation: 1
  rhythmicContrast: 0.8276942
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: Different Grind
