name: 'theDifferent Grind : Kind Coffee'
layout_spectrum: 0
typography_spectrum: 0
opengraph:
  type: ''
  appId: ''
color:
  brandColors:
    - '#080506'
    - '#E0DCD4'
    - '#443020'
    - '#CF842F'
    - '#9E9586'
  brandStrength: 0.4974937
  lightness: 0.4837093
  saturation: 1
  rhythmicContrast: 0.7249373
title: "Caffeine with a Conscience - not only is it\_Different, it's kind."
author:
  name: CaptainCu
  url: ''
  email: ''
content_rating:
  adult: false
