typography_spectrum: 0
content_rating:
  adult: false
color:
  brandColors:
    - '#080506'
    - '#E0DCD4'
    - '#443020'
    - '#CF842F'
    - '#9E9586'
  brandStrength: 0.4974937
  lightness: 0.4837093
  saturation: 1
  rhythmicContrast: 0.7249373
opengraph:
  image: null
  type: ''
  appId: ''
layout_spectrum: 0
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: CaptainCu
  url: ''
  email: ''
name: 'theDifferent Grind : Kind Coffee'
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: "Caffeine with a Conscience - not only is it\_Different, it's kind."
purpose: []
